- platform: template
  sensors:
    utility_room_motion_battery:
      value_template: "{{ states.zwave.vision_zp3111_multisensor_4in1.attributes.battery_level }}"
      friendly_name: "Utility room motion sensor battery"
      entity_id: zwave.vision_zp3111_multisensor_4in1
      unit_of_measurement: '%'
    upstairs_motion_battery:
      value_template: "{{ states.zwave.vision_zp3111_multisensor_4in1.attributes.battery_level_2 }}"
      friendly_name: "Upstairs motion sensor battery"
      entity_id: zwave.vision_zp3111_multisensor_4in1_2
      unit_of_measurement: '%'
    media_room_motion_battery:
      value_template: "{{ states.zwave.vision_zp3102_pir_motion_sensor.attributes.battery_level }}"
      friendly_name: "Media room motion sensor battery"
      entity_id: zwave.vision_zp3102_pir_motion_sensor
      unit_of_measurement: '%'


