# My Monoprice Z-wave motion sensors don't report motion as binary. This is a
# hack to create binary sensors off of the "alarm_level" reading.

- platform: template
  sensors:
    utility_room_motion:
      device_class: motion
      entity_id: sensor.vision_zp3111_multisensor_4in1_alarm_level
      friendly_name: 'Utility room motion'
      value_template: "{{ is_state('sensor.vision_zp3111_multisensor_4in1_alarm_level', '255') }}"
    upstairs_motion:
      device_class: motion
      entity_id: sensor.vision_zp3111_multisensor_4in1_alarm_level_2
      friendly_name: 'Upstairs motion'
      value_template: "{{ is_state('sensor.vision_zp3111_multisensor_4in1_alarm_level_2', '255') }}"
    entry_hallway_motion:
      device_class: motion
      entity_id: sensor.vision_zp3102_pir_motion_sensor_alarm_level
      friendly_name: 'Entry hallway motion'
      value_template: "{{ is_state('sensor.vision_zp3102_pir_motion_sensor_alarm_level', '255') }}"